# Generated by Django 4.2 on 2023-04-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czesne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('do_zaplaty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('naleznosc', models.FloatField(default=0)),
                ('czesne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.czesne')),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.klasa')),
            ],
        ),
    ]
