# Generated by Django 4.2 on 2023-05-16 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('kwota', models.FloatField()),
                ('tytul', models.CharField(max_length=50)),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.uczen')),
            ],
        ),
    ]
