# Generated by Django 4.2 on 2023-05-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='tytul',
            new_name='mazwa',
        ),
    ]
