# Generated by Django 4.2 on 2023-05-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_rename_tytul_status_mazwa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='mazwa',
            new_name='tytul',
        ),
    ]
