# Generated by Django 4.2.1 on 2023-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_rename_mazwa_status_tytul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('day_of_adding_statuses', models.CharField(max_length=2)),
            ],
        ),
    ]
